Added imprved fulltext search
wepublish/wepublish pull request #1124
Opened 2023-12-13 15:41 UTC by elias-summermatter

2023-12-14 12:22 UTC, Itrulia requested changes
Looking good but the tests are failing due to the changes

2023-12-27 07:19 UTC, antkiewiczk reviewed
Please fix the relevant tests 
<img width="660" alt="Screenshot 2023-12-27 at 08 18 17" src="https://github.com/wepublish/wepublish/assets/24550916/8f38094f-7472-460f-b284-f58a399bebb5">

2024-01-03 16:04 UTC, elias-summermatter commented
@antkiewiczk @Itrulia test should be fixed now

2024-01-05 14:41 UTC, Itrulia approved these changes

2024-01-09 05:57 UTC, tomaszdurka approved these changes

2024-01-11 09:34 UTC, merged