F/wpc 1145 improved docker build
wepublish/wepublish pull request #1150
Opened 2024-01-23 15:54 UTC by elias-summermatter

2024-01-25 11:43 UTC, antkiewiczk submitted a review, later dismissed

2024-01-25 14:49 UTC, Itrulia commented on package.json
> +    "docker:build:api": "npx nx run-many --targets=build --projects=api-example",
Imo don't think these are needed and we could just run `npx nx build api-example` in the dockerfile. I don't like adding simple commands to the package.json. What do others think?

There's a few other scripts I would get rid of too :D They are mostly there bc of historic reasons (yarn time and workspaces)

2024-01-30 07:58 UTC, Itrulia submitted a review, later dismissed

2024-01-30 14:53 UTC, Itrulia approved these changes

2024-01-31 07:59 UTC, Itrulia approved these changes

2024-01-31 10:11 UTC, tomaszdurka requested changes
@elias-summermatter Looks good!

As discussed let's change:
1. Allow to pass multiple tags for building/pushing api, editor and migration images
2. Authenticate to both ghcr and dockerhub in build-push jobs so we can push to both or any of them by specifying tags

2024-01-31 14:00 UTC, tomaszdurka approved these changes

2024-01-31 14:00 UTC, tomaszdurka commented on Dockerfile
> +COPY --chown=wepublish:wepublish  --from=build-api /wepublish/node_modules/bcrypt node_modules/bcrypt
whitespace

2024-01-31 14:44 UTC, Itrulia approved these changes

2024-01-31 14:45 UTC, merged