T/api user user role
wepublish/wepublish pull request #117
Opened 2020-12-22 16:05 UTC by penk85

API tests for User and User Role.

2020-12-24 18:05 UTC, faebebin approved these changes
Looks good. Everything works locally too.

2020-12-28 09:53 UTC, roosnic1 requested changes
Looks good. Just some improvements needed.

2020-12-29 18:59 UTC, roosnic1 approved these changes
Awesome. 👍🏾

2020-12-30 09:13 UTC, 0815pascal approved these changes

2020-12-30 14:09 UTC, merged