Mailgun improvements
wepublish/wepublish pull request #124
Opened 2021-01-02 12:54 UTC by roosnic1

2021-01-04 08:56 UTC, 0815pascal requested changes
It looks good, just one question

2021-01-04 08:56 UTC, 0815pascal commented on packages/api/src/mails/MailgunMailProvider.ts
> +        (err, res) => {
where are you using `res` ?

2021-01-04 09:24 UTC, penk85 submitted a review, later dismissed

2021-01-04 13:36 UTC, roosnic1 commented on packages/api/src/mails/MailgunMailProvider.ts
> +        (err, res) => {
Good point. Fixed it.

2021-01-04 13:46 UTC, bishoymelek approved these changes

2021-01-04 16:07 UTC, penk85 approved these changes

2021-01-04 19:10 UTC, bishoymelek approved these changes

2021-01-05 08:06 UTC, faebebin approved these changes
Looks good

2021-01-05 09:03 UTC, 0815pascal approved these changes

2021-01-05 09:31 UTC, merged