BABA-25: Add pagination to article list
wepublish/wepublish pull request #1267
Opened 2024-04-09 12:41 UTC by antkiewiczk

2024-04-11 06:59 UTC, Itrulia requested changes

2024-04-11 06:59 UTC, Itrulia commented on libs/article/website/src/lib/article-list/article-list.tsx
Article list should not have pagination. This is a job for the parent of article list.

2024-04-11 07:01 UTC, Itrulia commented on libs/article/website/src/lib/article-list/article-list.tsx
> +  useEffect(() => {
There's like 3 bugs in this useEffect, it's also not needed

2024-04-11 07:02 UTC, Itrulia commented on libs/article/website/src/lib/article-list/article-list.tsx
> +export const PaginationStyled = styled(Pagination)`
No styled post fix please. **Ever** when it gets exported.

2024-04-11 07:40 UTC, antkiewiczk commented on libs/article/website/src/lib/article-list/article-list.tsx
why is onVariablesChange passed to article-list? (why is it a prop?)

2024-04-11 08:22 UTC, Itrulia commented on libs/article/website/src/lib/article-list/article-list.tsx
So that you can implement pagination.

2024-04-11 08:22 UTC, Itrulia commented on libs/article/website/src/lib/article-list/article-list.tsx
> +export const PaginationStyled = styled(Pagination)`
Yes, but inside the website builder.

2024-04-11 11:57 UTC, Itrulia commented on libs/article/website/src/lib/article-list/article-list.tsx
> +export const PaginationStyled = styled(Pagination)`
It's part of the library but not the builder itself. So it can not be overridden. Checkout the WebsiteBuilderContext

2024-04-11 12:01 UTC, antkiewiczk commented on libs/article/website/src/lib/article-list/article-list.tsx
so you mean article-list-container? or should I create an override for article-list in babanews?

2024-04-15 06:50 UTC, Itrulia commented on apps/babanews/pages/a/index.tsx
> +  useEffect(() => {
Not needed and causes a double render, call onVariablesChange inside the onChange

2024-04-15 06:59 UTC, Itrulia commented on apps/babanews/pages/a/index.tsx
> +  useEffect(() => {
Actually no, the way this was implemented we need the setPage. But we can move this also into the onChange to not have a double render.

2024-04-15 07:00 UTC, Itrulia approved these changes

2024-04-15 08:11 UTC, merged