GRUP-12: Allow linking image blocks to a URL
wepublish/wepublish pull request #1307
Opened 2024-04-27 07:42 UTC by LukasSkywalker

This change allows adding the "linkUrl" to image blocks, which are then turned into hyperlinks to the specified URL. This allows turning images into ads that point to an external site.
The new linkUrl attribute is a bit of special case. All other content blocks allow changing the block attributes with the corresponding EditPanel. The image block is a bit different in that regard, and doesn't open the block attributes, but those of the underlying image.
This PR modifies the EditPanel to also expose the new linkUrl attribute in addition to the existing image attributes.

2024-04-29 07:14 UTC, michael-scheurer approved these changes

2024-04-29 07:45 UTC, antkiewiczk approved these changes

2024-04-29 07:48 UTC, antkiewiczk reviewed
Please add tests

2024-04-29 07:48 UTC, Itrulia requested changes
Please add a test case to the image-block story & run tests via `nx test image-website` to generate the snapshot.

2024-04-30 09:14 UTC, antkiewiczk approved these changes

2024-04-30 09:15 UTC, michael-scheurer submitted a review, later dismissed

2024-04-30 09:54 UTC, tomaszdurka submitted a review, later dismissed

2024-04-30 13:14 UTC, merged