SHARE-9: Allow media to inject custom Javascript code
wepublish/wepublish pull request #1335
Opened 2024-05-19 10:28 UTC by LukasSkywalker

With this change, media can enter custom Javascript code, for example for displaying ads or embedding analytics solutions, into their editor. The websites can embed the code by using one of the static script URLs, where the code from the editor is automatically served as a plain Javascript file. There is one setting for code that will be injected into the head, and one for code for the body tag.

The scripts are served separately from the API, but from the same server for two reasons:

1) Serving the code via GraphQL would make handling difficult and would require parsing the response, extracting the code, and embedding it into the page. Serving it directly as a "virtual" JS file makes embedding much easier.

2) This approach allows the scripts to be cached independently of the API calls, similar to a static asset.

For serving the scripts, the Express instance that hosts the API is used, and the scripts are loaded using an extra Express router.

2024-05-21 09:31 UTC, elias-summermatter requested changes

2024-05-21 09:31 UTC, elias-summermatter commented on libs/api/src/lib/static.ts
> +      res.setHeader('content-type', 'application/javascript')
Kann man hier noch entsprechende cache headers setzen? z.B sowas: 
Gerne auch andere werte sofern sinvoll/nicht sinvoll
Cache-Control: public, max-age 86400,

2024-05-21 09:31 UTC, elias-summermatter commented on apps/editor/src/app/locales/de.json
> +        "scripts": "Scripts aus unseriösen Quellen können schwerwiegende Sicherheitsprobleme verursachen und dazu führen, dass Anmeldedaten gestohlen werden."
Hier vielleicht auch noch erwähnen, dass es die gesamte Seite "zerschiessen" kann und man daher aufpassen muss

2024-05-21 09:31 UTC, elias-summermatter commented on apps/website-example/pages/_app.tsx
> +              src={publicRuntimeConfig.env.API_URL! + '/static/body.js'}
Kannst du das auch noch im website builder als Default einführen? Also das es auch für bajour, tsri babanews und so out of the box funktioniert?

2024-05-21 09:31 UTC, elias-summermatter commented on libs/api/src/lib/static.ts
> +        res.send('')
- Vielleicht verwenden von ETags?
- gzip: https://www.npmjs.com/package/express-gzip

2024-05-21 09:31 UTC, elias-summermatter commented on libs/api/src/lib/static.ts
> +      const script = await this.prismaClient.setting.findFirst({
- Expires header

2024-05-21 09:31 UTC, elias-summermatter commented on libs/api/src/lib/static.ts
> +      const script = await this.prismaClient.setting.findFirst({
- Last-Modified header

2024-05-21 09:31 UTC, elias-summermatter commented on libs/api/src/lib/static.ts
> +      const script = await this.prismaClient.setting.findFirst({
- "X-Content-Type-Options: nosniff" header

2024-05-21 09:31 UTC, elias-summermatter commented on libs/api/src/lib/static.ts
> +      const script = await this.prismaClient.setting.findFirst({
X-Frame-Options: DENY heder

2024-05-21 09:31 UTC, elias-summermatter commented on libs/api/src/lib/static.ts
> +      const script = await this.prismaClient.setting.findFirst({
Referrer-Policy: no-referrer header

2024-05-21 09:31 UTC, elias-summermatter commented on libs/api/__tests__/specs/static.test.ts
> +describe('static scripts', () => {
Also add e test that checks that all headers are set correctly

2024-05-22 06:04 UTC, elias-summermatter approved these changes

2024-05-22 08:54 UTC, merged

2024-05-27 07:09 UTC, Itrulia commented
@elias-summermatter @michael-scheurer @LukasSkywalker this has massive impact on performance for website and I would have loved to be added to the review to this.


We load now a script regardless if there's anything added to it, which blocks rendering of HTML until the API answers. The `beforeInteractive` also loads before the app loads which is a huge problem. It should have been `afterInteractive` & `lazyOnload`.

2024-05-27 07:10 UTC, Itrulia commented
Ausserdem wurde es in API v1 style (express) implementiert und nicht im neuem Nestjs backend, heisst also einfach mehr legacy code der nun migriert werden muss.

2024-05-27 07:28 UTC, elias-summermatter commented
@LukasSkywalker kannst du dir die Anmerkungen von Karl anschauen und gegebenenfalls noch fixen. Vielleicht wäre es sinnvoll, wenn ihr kurz zusammen telefoniert, geht vielleicht schneller. :-)
Guten Start in die neue Woche wünsche ich.

2024-05-28 05:46 UTC, LukasSkywalker commented
Ich schlage vor, dass wir diese Änderung rückgängig machen, bis wir das diskutiert und wir eine Lösung haben. Nicht, dass wir andere Stories oder Deployments blockieren. Gut? @elias-summermatter @Itrulia

2024-05-28 13:05 UTC, Itrulia commented
Imo reverten brauchts nicht, nicht das schlimmste. Nur wichtig im Hinterkopf zu bewahren & zu fixen.