enh/BA-133 payrexx subscription
wepublish/wepublish pull request #1337
Opened 2024-05-21 08:53 UTC by michael-scheurer

2024-05-21 08:59 UTC, elias-summermatter approved these changes

2024-05-21 09:00 UTC, elias-summermatter requested changes
Tests are failing

2024-05-28 06:56 UTC, Itrulia commented on libs/membership/website/src/lib/subscribe/subscribe-container.tsx
> +import {useRouter} from 'next/router'
Can't access framework specific things inside website builder.

2024-05-28 06:58 UTC, Itrulia commented on libs/membership/website/src/lib/invoice-list/invoice-list-item.tsx
> +                href={`/mitmachen?memberPlanBySlug=${subscription?.memberPlan.slug}&upsell=true&cancelSubscriptionId=${subscription?.id}`}>
This URL is bajour specific only.

2024-07-02 16:17 UTC, michael-scheurer commented on libs/membership/website/src/lib/subscribe/subscribe-container.tsx
> +    deactivateSubscriptionId?: string
See comment above what this deactivateSubscriptionId does. It's basically a api functionality and very useful in this use case for Bajour but is also used for other use cases at Hauptstadt.

2024-07-02 16:19 UTC, michael-scheurer commented on libs/membership/website/src/lib/invoice-list/invoice-list-item.tsx
> +                href={`/mitmachen?memberPlanBySlug=${subscription?.memberPlan.slug}&upsell=true&deactivateSubscriptionId=${subscription?.id}`}>
Read comment above in the code. I know this is a Bajour specific url for now. We can change it if needed. Params wouldn't hurt anyway. Thinking about moving those filter params to standard functionality of Website Builder. Use cases would be the same for other media.

2024-07-02 16:21 UTC, michael-scheurer commented on libs/membership/website/src/lib/subscribe/subscribe-container.tsx
> +        cancelSubscriptionId={cancelSubscriptionId as string | undefined}
See comments in the code now as well as the renaming.

2024-07-03 12:46 UTC, elias-summermatter approved these changes

2024-07-03 12:46 UTC, merged