Pagination for tables and API
wepublish/wepublish pull request #143
Opened 2021-01-22 10:34 UTC by roosnic1

2021-01-22 11:21 UTC, faebebin approved these changes
Looks good. But I am not so deep into API yet ;)

2021-01-25 09:50 UTC, 0815pascal requested changes
Looks good, just two tiny things and I noticed that you forgot to add the German and French translation files.

2021-01-25 09:50 UTC, 0815pascal commented on packages/editor/src/client/routes/userList.tsx
> +            <HeaderCell>{t('email')}</HeaderCell>
I would rather use here `userList.overview.email` in order to be consistent with the rest

2021-01-25 09:50 UTC, 0815pascal commented on packages/editor/src/client/routes/userList.tsx
> +            <HeaderCell>{t('action')}</HeaderCell>
I would rather use here `userList.overview.action` in order to be consistent with the rest

2021-01-25 12:50 UTC, penk85 approved these changes

2021-01-25 18:43 UTC, faebebin approved these changes
Looks good.

2021-01-25 22:00 UTC, bishoymelek requested changes

2021-01-26 09:00 UTC, roosnic1 commented on packages/api/src/db/user.ts
> +export interface UserSubscriptionPeriodInput {
It's the same but they might change in the future. One is to handle the input and the other is the whole representation.

2021-01-26 09:23 UTC, merged