feat: implemented hot & trending, google analytics
wepublish/wepublish pull request #1519
Opened 2024-09-17 12:03 UTC by Itrulia

1. Datasource for hot&trending is configureable
2. Only GA has been implemented for now
3. Can be accessed via API or via TeaserListBlock

2024-09-17 12:04 UTC, Itrulia commented on apps/mannschaft/pages/a/[slug].tsx
Reverted tag in url since I had to touch this file anyway

2024-09-17 12:04 UTC, Itrulia commented on apps/mannschaft/pages/a/[slug].tsx
> +  // Shows the first 4 blocks (usually title, image, richtext + ad) and hides the rest
Updated this due to the ad block being the 3rd block now, so no text as teaser was shown.

2024-09-17 12:04 UTC, Itrulia commented on apps/mannschaft/pages/index.tsx
> +    client.query({
Added for SSR :)

2024-09-17 12:05 UTC, Itrulia commented on libs/api/src/lib/context.ts
Added it to context so I have access to it in the teaser list block

2024-09-24 15:09 UTC, michael-scheurer requested changes
I really like that you integrated GA in our api. That is very nice an re-usable. Thank you.
I left two comments.
And one more question: would you mind to provide a screenshot how it looks on mobile and desktop for mannschaft?

2024-09-24 15:23 UTC, Itrulia commented on libs/api/src/lib/graphql/blocks.ts
> +                    nodes: await hotAndTrendingDataSource.getMostViewedArticles({skip, take})
The existing implementation already sorts by publishedAt, this shouldnt change anything

2024-09-24 15:28 UTC, Itrulia commented
The UI already exists, you can see it on tsri or on mannschaft. I just filled it with data.

Good catch with the false value, should probably prevent a bug.


If no GA creds are set it will return an empty array and log a warning. Implemented this when I locked myself out of a page due to errors :D

2024-09-25 08:56 UTC, michael-scheurer approved these changes

2024-09-25 10:54 UTC, merged