feat(website): improve profile and navbar for members
wepublish/wepublish pull request #1681
Opened 2024-11-25 15:12 UTC by Itrulia

1. Also fixed issue with re-using apollo client
2. Also changed Gruppetto /abo to /mitmachen
3. Also changed Gruppetto to use the emotion cache

2025-01-07 11:00 UTC, michael-scheurer requested changes
Heavily improved, and well done. Here are my findings:
- Given, that I am not logged-in and would like to become a member. If the payment provider throws an error (in this case for testing purposes with wrong credentials), an account as well as a subscription are created. There are two problems though:
a) User doesn't see, that he/she has actually a valid login. Solution imo: log-in user and redirect him/her to the set-up failure page.
b) User will intuitively click again on the subscribe button (probably several times) and each time it creates a new unpaid subscription => Update user state and subscriptions. Also update with "open invoice" within the menu
![image](https://github.com/user-attachments/assets/e1153552-e842-4188-bd9a-0137ee32078b)

![image](https://github.com/user-attachments/assets/b45bf44d-a087-413f-bcac-df647469d01f)

![image](https://github.com/user-attachments/assets/9db92b4a-4ee7-48c7-b617-9cd120482c46)

- Open invoice should come with a colored frame and the same exclamation icon as the menu button. See miro sketches.
![image](https://github.com/user-attachments/assets/2c9cdf19-f75a-4b8d-9567-11d126ee4276)

![image](https://github.com/user-attachments/assets/3fc9ee20-9ec8-49d7-bf02-8864368a29c1)

- Found another bug. Given the following settings:
a) Create a stripe payment provider within the editor using standard dev environment.
![image](https://github.com/user-attachments/assets/84773f23-245b-4199-bc01-182f971fc6c5)
b) create a subscription with this stripe pp
![image](https://github.com/user-attachments/assets/01bb580b-9fb4-4e6b-9e17-c748328109ee)
c) Create that subscription. You are logged-in but without any error but user stays on the subscription form and will likely hit the btn again and again and pile up his/her subscriptions.
![image](https://github.com/user-attachments/assets/0e8b8b2e-c9f8-430a-b949-9a68afc8041c)

- "Member werden"-Button and "Offene Rechnung"-Button should not appear at the same time.
![image](https://github.com/user-attachments/assets/79e778d0-f326-4feb-8a52-5292f1e3c0a8)

- Check mobile. Imo logout btn could or should be placed elsewhere but not in the same line with the other btns.
![image](https://github.com/user-attachments/assets/cf2e4968-3689-4236-acc8-bcf0283b2fbb)

More to come ;)

2025-01-07 16:41 UTC, michael-scheurer commented
- Problem with "Offene Rechnung" on mobile
![image](https://github.com/user-attachments/assets/1ef1ba4e-b62d-43da-833c-587e6493e98f)
=> As a solution I would probably shorten it to "Rechnung"
![image](https://github.com/user-attachments/assets/e622a1cd-021c-4b94-9338-0d60472b1eda)

- Also the invoices and subscriptions on mobile are too much spaced around. Also difficulties in reading the text.
![image](https://github.com/user-attachments/assets/3ec2ffb1-c197-4980-9f47-68cff12901cb)

2025-01-07 16:45 UTC, michael-scheurer commented
- If I have a single active subscription on mobile, looks wired.
![image](https://github.com/user-attachments/assets/5620a692-ce39-4bbe-9dda-ceb14e45c407)

- Inconsistency in naming. It should be "Mein Konto". Instead with a single active subscription it is "Mein Account".
![image](https://github.com/user-attachments/assets/3b2778df-615b-460b-988b-0dab20d6ad94)

2025-01-07 16:54 UTC, michael-scheurer requested changes

2025-01-07 16:54 UTC, michael-scheurer commented on libs/api/src/lib/graphql/subscription-public.ts
> +        return (
We could make this logic re-usable and refactor it in a separate function and use it among the code.

2025-01-07 16:54 UTC, michael-scheurer commented on libs/membership/website/src/lib/has-active-subscription.tsx
> +        subscription =>
This logic is implemented manually all over the code. We could re-use it in a dedicated function.

2025-01-07 16:54 UTC, michael-scheurer commented on libs/membership/website/src/lib/has-unpaid-invoices.tsx
> +    () => data?.invoices.some(invoice => !invoice.canceledAt && !invoice.paidAt),
same logic used all over the code. we could start sharing a re-usable function for that ;)

2025-01-07 16:54 UTC, michael-scheurer commented on libs/membership/website/src/lib/subscription-list/__snapshots__/subscription-list-container.spec.tsx.snap
> +          Kein has noch kein aktives Abo.
Typo. Should be "Du hast noch kein aktives Abo."

2025-01-07 16:54 UTC, michael-scheurer commented on libs/membership/website/src/lib/subscription-list/__snapshots__/subscription-list.spec.tsx.snap
> +          Kein has noch kein aktives Abo.
dito

2025-01-07 16:54 UTC, michael-scheurer commented on libs/membership/website/src/lib/subscription-list/subscription-list.tsx
> +              Kein has noch kein aktives Abo. <Link href={subscribeUrl}>Jetzt ein Abo lösen.</Link>
dito with typo

2025-01-07 16:54 UTC, michael-scheurer commented on libs/navigation/website/src/lib/navbar/navbar.tsx
> +              Offene Rechnung
```suggestion
              Rechnung
```

2025-01-07 17:04 UTC, michael-scheurer requested changes

2025-01-07 17:04 UTC, michael-scheurer commented on libs/api/src/lib/graphql/subscription-public.ts
> +          +add(new Date(), {months: 1}) > +subscription.paidUntil &&
Logic doesn't work as expected. Either in front-end or here. Please test.

Tested 7th of January 2025 for the following screenshot. And also tested with paidUntil 5th of January and 5th of March. None of them works.
![image](https://github.com/user-attachments/assets/f3b35025-c384-4cd8-8ec6-98ec936b6cf2)

2025-01-08 15:06 UTC, Itrulia commented on libs/api/src/lib/graphql/subscription-public.ts
> +        return (
And use it where?

2025-01-08 15:06 UTC, Itrulia commented on libs/membership/website/src/lib/has-active-subscription.tsx
> +        subscription =>
This is the dedicated function.

2025-01-08 15:08 UTC, Itrulia commented on libs/membership/website/src/lib/has-unpaid-invoices.tsx
> +    () => data?.invoices.some(invoice => !invoice.canceledAt && !invoice.paidAt),
This is the re-usable function for that.

2025-01-08 15:45 UTC, Itrulia commented on libs/api/src/lib/graphql/subscription-public.ts
> +          +add(new Date(), {months: 1}) > +subscription.paidUntil &&
The logic was actually correct, but the query above for the unpaid invoice wasn't

2025-01-21 16:25 UTC, michael-scheurer commented on libs/membership/website/src/lib/has-unpaid-invoices.tsx
> +    () => data?.invoices.some(invoice => !invoice.canceledAt && !invoice.paidAt),
I can live with it. In my code I just try to make life easier / safer for the following. So, that my fellows don't need to care about the fact, that he has to check for canceledAt and paidAt. I would probably just go with something like this:

`export function isActiveInvoice (invoice: Invoice): boolean => !invoice.canceledAt && !invoice.paidAt`

This is maybe because I am coming from OOP, where you would have such a function within the Invoice class. Defined it once, used it everywhere with exact same logic.

2025-01-22 10:18 UTC, closed without merging