SHARE-30: Allow to resubscribe for user without authentication
wepublish/wepublish pull request #1687
Opened 2024-12-02 00:49 UTC by tomaszdurka

Allow to resubscribe users without initial login.

We need to allow guest users to resubscribe easily (techinically providing only a `userId` in the mitmachen url).

We will use `/mitmachen` page. Normally this page:

- For guests allows to register as new user and subscribe (shows additional registration data, allowing user to create account and subscribe).
    - This sends email about created account and created subscription.
- For logged in users it allows to subscribe as that user (without need of account creation)
    - This sends email about created subscription.

Now we want to add 3rd scenario where:

- For guests (with provided `userId` as query param) allows to subscribe as that user (without need of account creation or logging in).
- The flow will be a bit different
    - **This subscription will be “unconfirmed” from start.**
    - **It will send different email: RESUBSCRIBE** (with content to confirm subscription)
    - Once confirmed the flow will go like with normal subscription, sending email about created subscription.

Additional changes to other flows.

- We are introducing new `confirmed` stated on subscription. This will be used for the resubscribe flow. However it needs to be considered in all the background jobs for subscriptions.

Technical changes:

- [x]  Add `confirmed` field to `subscription` table
- [x]  Add endpoint for `resubscribe` with extra email for `confirmation`
- [x]  Modify `Subscribe` forms to consider resubscribe case
- [x]  Modify subscription background jobs to consider `confirmed` state of subscriptions

2024-12-02 09:55 UTC, Itrulia commented on libs/membership/website/src/lib/subscribe/subscribe.tsx
> +          {paymentText} {donate?.(selectedMemberPlan) ? 'spenden' : 'abonnierens'}
Typo

2024-12-02 09:55 UTC, Itrulia commented on libs/membership/website/src/lib/subscribe/subscribe.tsx
> +import {useRouter} from 'next/router'
Shouldnt be accessed outside of pages

2025-01-20 07:28 UTC, elias-summermatter requested changes

2025-01-20 07:28 UTC, elias-summermatter commented on libs/api/prisma/migrations/20241211094306_add_subscribe_event_resubscribe/migration.sql
> +        'RESUBSCRIBE',
Why does this is named "RESUBSCRIBE" isnt it more like "CONFIRMSUBSCRIPTION"?

2025-01-20 07:28 UTC, elias-summermatter commented on libs/api/prisma/schema.prisma
> +  RESUBSCRIBE
Same here

2025-01-20 07:28 UTC, elias-summermatter commented on libs/api/prisma/migrations/20241211094306_add_subscribe_event_resubscribe/migration.sql
> +ALTER TYPE "SubscriptionEvent" ADD VALUE 'RESUBSCRIBE';
Same here

2025-01-20 07:28 UTC, elias-summermatter commented on libs/api/src/lib/memberContext.ts
> +      ? SubscriptionEvent.RESUBSCRIBE
Same here

2025-01-20 07:28 UTC, elias-summermatter commented on libs/membership/api/src/lib/periodic-job/periodic-job.service.ts
> +        confirmed: true
Don't we want custom mails to be sent for non-confirmed Subscriptions? And just deactivate charging?

2025-01-20 07:29 UTC, elias-summermatter commented
Can @Itrulia you also take a look at the frontend stuff?

2025-01-21 11:15 UTC, Itrulia requested changes

2025-01-21 11:15 UTC, Itrulia commented on libs/membership/website/src/lib/subscribe/subscribe-container.tsx
> +      window.location.href = '/thank-you'
Shouldn't the payment provider redirect us? It's set what page in the memberPlan

2025-01-21 11:15 UTC, Itrulia commented on libs/membership/website/src/lib/subscribe/subscribe.tsx
> +      }
```suggestion
      }
      
```

2025-01-21 11:15 UTC, Itrulia commented on libs/membership/website/src/lib/subscribe/subscribe.tsx
> +      )}
```suggestion
      )}
      
```

2025-01-21 11:15 UTC, Itrulia commented on libs/membership/website/src/lib/subscribe/subscribe.tsx
> +            {`Hallo ${defaults?.firstName ?? ''} ${defaults?.name ?? ''}`.trim()}, willkommen
Don't think we need to trim, no? since it's note code multiple spaces should be turned into 1 or am I wrong?

2025-02-03 16:39 UTC, Itrulia commented on libs/membership/website/src/lib/subscribe/subscribe-container.tsx
> +              window.location.href = selectedMemberplan?.confirmationPage?.url ?? ''
I think the URL should be returned by the resubscribe action, and the onCompleted action should probably in the declaration above.

2025-02-04 10:21 UTC, michael-scheurer requested changes
Unfortunately, found a bug. In the editor, when I go to _Subscription Plans / Default Mailing_, the following error happens and a blank page is shown. Likely related to v1/v2 schema conflicts.

Invalid `prisma.subscriptionFlow.findMany()` invocation:\n\n\nValue 'RESUBSCRIBE' not found in enum 'SubscriptionEvent'

![image](https://github.com/user-attachments/assets/6263f3c0-5f11-4e4b-9efc-d5b1166e7747)

2025-02-04 11:14 UTC, elias-summermatter requested changes

2025-02-04 11:14 UTC, elias-summermatter commented on libs/membership/api/src/lib/subscription-payments/subscription-payments.service.ts
> +          confirmed: true
You could maybe write a testcase here to test that if confirmed =  false its not returned

2025-02-04 11:17 UTC, elias-summermatter commented
@tomaszdurka, if you have written the additional test for membership, tested the workflow thoroughly, and addressed the bug Michael found, you can merge it.

2025-02-09 17:45 UTC, merged