Magic module error documentation
wepublish/wepublish pull request #173
Opened 2021-02-08 11:24 UTC by HanaAyman

Added in FAQ.md the solution to solve an error " cannot find magic module "

2021-02-08 11:48 UTC, bishoymelek requested changes

2021-02-08 11:48 UTC, bishoymelek commented on package.json
> -    "node": "^12.0.0",
I guess this is needed

2021-02-08 12:29 UTC, roosnic1 requested changes

2021-02-08 12:29 UTC, roosnic1 commented on FAQ.md
> +#### Q: What do I do if 'exapmles/media' doesn't run and I receive the error `Error: Cannot find module '../build/Release/magic'` in the terminal and I receive an error when trying to install this mo
I would also mention that it's a windows specific problem.

2021-02-08 22:32 UTC, penk85 commented on FAQ.md
> +#### Q: What do I do if I'm using Windows and 'exapmles/media' doesn't run and I receive the error `Error: Cannot find module '../build/Release/magic'` in the terminal and I receive an error when try
just a small typo on word examples

2021-02-08 22:34 UTC, penk85 submitted a review, later dismissed

2021-02-09 08:40 UTC, roosnic1 approved these changes

2021-02-09 08:44 UTC, 0815pascal approved these changes

2021-02-09 09:26 UTC, bishoymelek approved these changes

2021-02-09 11:04 UTC, merged