Added a new seoTitle field to the article metadata
wepublish/wepublish pull request #192
Opened 2021-02-17 16:35 UTC by roosnic1

2021-02-17 18:07 UTC, 0815pascal requested changes
Looks good, but translations for German and French are missing

2021-02-18 08:25 UTC, penk85 approved these changes

2021-02-18 08:33 UTC, HanaAyman approved these changes

2021-02-18 09:36 UTC, bishoymelek approved these changes

2021-02-18 09:44 UTC, roosnic1 commented
@0815pascal we don't translate to german or french at the moment

2021-02-18 09:44 UTC, merged