B/wpc 224 logout
wepublish/wepublish pull request #196
Opened 2021-02-24 14:20 UTC by penk85

Redirect to logout if unauthenticated.

2021-02-24 15:22 UTC, roosnic1 requested changes
looks very good. just a little cleanup

2021-02-24 15:22 UTC, roosnic1 commented on packages/editor/src/client/index.tsx
> +        console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`)
Please comment the `console.log` out. It's good for debugging but we don't need that in production.

2021-02-24 15:22 UTC, roosnic1 commented on packages/editor/src/client/index.tsx
> +      if (networkError) console.log(`[Network error]: ${networkError}`)
Please comment the `console.log` out. It's good for debugging but we don't need that in production.

2021-02-24 19:18 UTC, 0815pascal approved these changes

2021-02-25 11:13 UTC, HanaAyman approved these changes

2021-02-25 14:25 UTC, roosnic1 approved these changes

2021-02-26 07:54 UTC, merged