Enhanced User address
wepublish/wepublish pull request #198
Opened 2021-02-25 17:10 UTC by roosnic1

WPC-241. This PR adds two new fields "company" and "address2" to the user address. For the sake of consistency i renamed the field "street" to "address". For this we have a migration but this makes the PR also breaking because if somebody already uses this in a query or mutation they have to change that.

2021-02-25 20:51 UTC, 0815pascal submitted a review, later dismissed

2021-02-26 08:00 UTC, faebebin requested changes

2021-02-26 08:47 UTC, roosnic1 commented on packages/api/src/graphql/user.ts
>      zipCode: {type: GraphQLNonNull(GraphQLString)},
good point. will change.

2021-02-26 12:38 UTC, faebebin approved these changes

2021-02-26 14:16 UTC, bishoymelek approved these changes

2021-02-27 12:35 UTC, merged