f/wpc-266-add-getCommentUrl-in-UrlAdapter-interface
wepublish/wepublish pull request #227
Opened 2021-03-25 11:28 UTC by HanaAyman

2021-03-26 08:03 UTC, roosnic1 requested changes
looks good just some tiny changes

2021-03-26 08:03 UTC, roosnic1 commented on packages/api/__tests__/utility.ts
> +      return `https://editor.demo.wepublish.media/comments/a/${item.id}/${item.slug}/${comment.id}`
I know this is only a test but the URL would still not be on the editor. It would be more something like `https://demo.wepublish.media/...`

2021-03-26 08:03 UTC, roosnic1 commented on packages/api/__tests__/utility.ts
> +    return `https://editor.demo.wepublish.media/comments/${item.slug}/${comment.id}`
same here.

2021-03-26 08:57 UTC, roosnic1 approved these changes
🦖

2021-03-29 09:41 UTC, bishoymelek approved these changes
:tada:

2021-03-29 10:29 UTC, merged