F/wpc 231 234 extensions and i18n support
wepublish/wepublish pull request #245
Opened 2021-04-13 16:42 UTC by DenisHuber

Implementation of the following features (wip):
- API, Editor extensible
- Custom Content Models
- Multi-language support
- Reference Type implementation
- Browsers Credential Manager Feature implementation

2021-04-21 13:22 UTC, roosnic1 requested changes

2021-04-21 13:22 UTC, roosnic1 commented on packages/editor/src/client/routes/contentEditor.tsx
> +                {t('articleEditor.overview.back')}
i would avoid using translation strings from `articleEditor`. Also i think some of the translations in here are available in the globals.

2021-04-21 13:22 UTC, roosnic1 commented on packages/editor/src/client/routes/contentList.tsx
> +  function loadMore() {
i strongly recommend using the the pagination components as in the article and page list. I already commented about this in the API. As soon as you want to sort the `fetchMore` is useless. And

2021-04-21 13:22 UTC, roosnic1 commented on packages/editor/src/client/routes/contentList.tsx
> +            {/* <DescriptionListItem label={t('articles.panels.updatedAt')}>
why commented out?

2021-04-21 13:22 UTC, roosnic1 commented on packages/editor/src/client/routes/memberPlanList.tsx
> +  // const speaker = (
i think this can be deleted

2021-04-21 13:22 UTC, roosnic1 commented on packages/editor/src/index.ts
> +export * from './client/client'
why only those exports?

2021-04-21 13:22 UTC, roosnic1 commented on packages/editor/src/client/Editorcontext.tsx
> +export const ConfigContext = React.createContext<EditorConfig | undefined>(undefined)
where is this used?

2021-04-21 14:14 UTC, DenisHuber commented on packages/api/src/business/contentModelBusiness.ts
> +        revision: 1,
revision handling is not yet implemented

2021-04-21 14:20 UTC, DenisHuber commented on packages/api/src/business/contentModelBusiness.ts
> +        delete ref.record
It is checked if the reference is valid (check if record of this type and id exists in the db)

2021-04-21 14:28 UTC, DenisHuber commented on packages/api/src/business/contentModelBusiness.ts
> +    authorise(CanCreateArticle, roles)
Will do

2021-04-21 14:44 UTC, DenisHuber commented on packages/api/src/db/content.ts
> +export enum DBContentState {
Totally agree. Needs to be discussed for the upcoming feature implementations --> release flow & revisions

2022-01-24 09:44 UTC, roosnic1 commented
closing PR because not relevant anymore.

2022-01-24 09:44 UTC, closed without merging