wpc-421 graphql description
wepublish/wepublish pull request #285
Opened 2021-06-14 13:25 UTC by HanaAyman

This pull request is to add description to the graphQL public mutations and queries.

2021-06-15 07:40 UTC, penk85 commented on packages/api/src/graphql/mutation.public.ts
> +        "This mutation allows to reset the password by sending the user's email and a login link will be sent to that email.",
Maybe better worded:  "This mutation allows to reset the password by accepting the user's email and sending a login to that email.",

2021-06-15 07:42 UTC, penk85 commented on packages/api/src/graphql/mutation.public.ts
> +        "This mutation allows to update the user's password by entering the new password and the repeated new password and gives an error if the passwords don't match or if the user is not authentica
Maybe better in a split sentence:
"This mutation allows to update the user's password by entering the new password. The repeated new password gives an error if the passwords don't match or if the user is not authenticated."

2021-06-15 07:44 UTC, penk85 commented on packages/api/src/graphql/query.public.ts
> +      description: 'This query takes either the ID or the slug and returns the peer profile.',
Just a note that you sometimes write ID lowercase, and probably best to be consistent.

2021-06-15 07:45 UTC, penk85 commented on packages/api/src/graphql/query.public.ts
> +      description: 'This query takes either the ID, slug ot token and returns the article.',
ot -> typo

2021-06-15 07:53 UTC, penk85 commented on packages/api/src/graphql/mutation.public.ts
> +        "This mutation allows to create a user session by taking the user's credentials email and password as an input and returns a session with token",
For consistency sake probably best to end sentences with a .

2021-06-15 08:37 UTC, roosnic1 requested changes
looks good. I commented some tiny change requests

2021-06-15 08:37 UTC, roosnic1 commented on packages/api/src/graphql/mutation.public.ts
> +      description: 'This mutation checks if the session is authenticated and returns a boolean.',
this mutation **revokes** the active session. The sessions gets deleted.

2021-06-15 08:37 UTC, roosnic1 commented on packages/api/src/graphql/mutation.public.ts
> +        "This mutation allows to reset the password by accepting the user's email and sending a login to that email.",
...sending a login link to...

2021-06-15 12:37 UTC, penk85 approved these changes
:+1:

2021-06-17 19:29 UTC, bishoymelek approved these changes
:tada:

2021-06-18 11:37 UTC, roosnic1 approved these changes
🎉

2021-06-18 14:06 UTC, merged