Add properties tab to metadata
wepublish/wepublish pull request #294
Opened 2021-07-01 08:31 UTC by penk85

WPC-422: Add tab in metadata on articles and pages which gives allows setting key value properties.

2021-07-01 08:47 UTC, bishoymelek submitted a review, later dismissed
:tada:

2021-07-01 23:05 UTC, HanaAyman approved these changes

2021-07-05 08:02 UTC, roosnic1 requested changes
very good work just some minor changes requested.

2021-07-05 08:02 UTC, roosnic1 commented on packages/editor/src/client/panel/articleMetadataPanel.tsx
> +            <ListInput
I think we should also add a little info text here similar to the social media metadata. It should read something like "Properties can be set per article/page. Public properties are accessible through the public API"

2021-07-05 11:12 UTC, roosnic1 approved these changes
🎉

2021-07-05 11:14 UTC, HanaAyman approved these changes

2021-07-05 12:19 UTC, merged