wpc-211-comment-length-validation
wepublish/wepublish pull request #309
Opened 2021-07-13 13:44 UTC by HanaAyman

2021-07-16 15:05 UTC, penk85 commented on packages/api/src/utility.ts
> +    throw new Error(`Comment Length should be maximum of 1000 characters`)
"length" lowercase

2021-07-16 15:10 UTC, penk85 commented on examples/website/src/shared/molecules/commentTemplate.tsx
> +      if(error.message === "Comment Length should be maximum of 1000 characters"){
Is there a more stable way of checking this than comparing strings? Can you setCommentStateInfo to be error.message?

2021-07-16 15:11 UTC, penk85 requested changes
Just some comments

2021-07-27 08:59 UTC, HanaAyman commented
This pull request is to change the pages icon in the menu.

2021-07-27 09:58 UTC, bishoymelek submitted a review, later dismissed
:tada:

2021-07-27 10:40 UTC, roosnic1 requested changes
looks good. just some changes

2021-07-27 10:40 UTC, roosnic1 commented on packages/api/src/utility.ts
> +export function validateCommentLength(text: RichTextNode[]) {
i don't think you need an extra function for this. You can just directly compare the `countRichtextChars` return value to the comment length limit where you call this.

2021-07-27 10:40 UTC, roosnic1 commented on packages/api/src/utility.ts
> +  if (charCount > 1000) {
Please create a constant for the 1000

2021-07-27 10:40 UTC, roosnic1 commented on packages/api/src/utility.ts
> +    throw new Error(`Comment length should be maximum of 1000 characters`)
Please check the file `packages/api/src/error.ts` and add an error like this.

2021-07-28 07:22 UTC, roosnic1 requested changes
last small changes

2021-07-28 07:22 UTC, roosnic1 commented on packages/api/src/error.ts
> +    super(`Comment length should not exceed 1000 characters.`, ErrorCode.CommentLengthError)
you should use the `MAX_COMMENT_LENGTH` constant here.

2021-07-28 07:22 UTC, roosnic1 commented on packages/api/src/graphql/mutation.public.ts
> +          return
the `return` is not needed. After the throw it will abort anyway until something is catching the error.

2021-07-28 11:50 UTC, roosnic1 commented on packages/api/src/error.ts
> +    super(`Comment length should not exceed ` + MAX_COMMENT_LENGTH + ` characters.`, ErrorCode.CommentLengthError)
With [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) you can write the line like this `.... should not exceed ${MAX_COMMENT_LENGTH} characters....`

2021-07-28 14:02 UTC, roosnic1 submitted a review, later dismissed
👍🏾

2021-07-30 09:02 UTC, bishoymelek approved these changes
:tada:

2021-08-02 08:30 UTC, penk85 submitted a review, later dismissed

2021-08-02 10:04 UTC, bishoymelek approved these changes
:tada:

2021-08-03 09:34 UTC, penk85 approved these changes

2021-08-03 10:50 UTC, roosnic1 approved these changes
👍🏾

2021-08-03 10:51 UTC, merged