Add image cta in peer profile
wepublish/wepublish pull request #310
Opened 2021-07-13 17:49 UTC by penk85

WPC-434: Add an image Call To Action (image and URL) inside the peer profile.

2021-07-14 08:00 UTC, bishoymelek approved these changes
:tada:

2021-07-14 09:26 UTC, HanaAyman approved these changes

2021-07-14 11:39 UTC, roosnic1 commented on packages/api/__tests__/specs/__snapshots__/peer.ts.snap
> +      "callToActionImageURL": null,
here it's `null` and in the test snapshot above it's `""`. I think it should be the same in both.

2021-07-14 11:53 UTC, roosnic1 requested changes

2021-07-14 11:53 UTC, roosnic1 commented on packages/editor/src/client/panel/peerProfileEditPanel.tsx
> +  const [callToActionImageID, setCallToActionImageID] = useState<PeerProfileImage>()
I'm not sure if the `PeerProfileImage` is the right type. It's used for the peer profile and you have here just a normal image.

2021-07-14 11:53 UTC, roosnic1 commented on packages/editor/src/client/panel/peerProfileEditPanel.tsx
> +        {isLogoChange
this is a lot of repetitive code i think you can put must of the logic in side the `id={...}` expression.

2021-07-15 15:43 UTC, HanaAyman approved these changes

2021-07-16 07:40 UTC, roosnic1 requested changes

2021-07-16 07:40 UTC, roosnic1 commented on packages/api-db-mongodb/src/db/peer.ts
> +        callToActionImageID: undefined,
they are undefined by default. I think you should set them to `''`

2021-07-16 07:40 UTC, roosnic1 commented on packages/editor/src/client/panel/peerProfileEditPanel.tsx
> +      setCallToActionImage(data?.peerProfile?.callToActionImage ?? undefined)
you don't need the `?? undefined` if you use them before the dots.

2021-07-26 14:43 UTC, HanaAyman approved these changes

2021-07-27 08:20 UTC, roosnic1 submitted a review, later dismissed

2021-08-02 10:00 UTC, bishoymelek approved these changes
:tada:

2021-08-02 11:07 UTC, HanaAyman approved these changes

2021-08-03 07:17 UTC, roosnic1 approved these changes
👍🏾

2021-08-03 11:16 UTC, merged