wpc-478
wepublish/wepublish pull request #340
Opened 2021-08-09 12:54 UTC by HanaAyman

This pull request is to show the maximum length of the comments.

2021-08-10 07:22 UTC, penk85 submitted a review, later dismissed

2021-08-11 11:32 UTC, bishoymelek requested changes

2021-08-11 11:32 UTC, bishoymelek commented on examples/website/src/shared/molecules/commentTemplate.tsx
> +  const maxCommentLength = 1000
I suggest this to be from an environment variable. what do you think? @HanaAyman

2021-08-11 11:32 UTC, bishoymelek commented on examples/website/src/shared/molecules/commentTemplate.tsx
> +            {' '}
Can you clean this one please? for readability

2021-08-11 11:32 UTC, bishoymelek commented on examples/website/src/shared/molecules/commentTemplate.tsx
> +  function countRichtextChars(blocksCharLength: number, nodes: any) {
I am not sure but i remember we already have a similar function?

2021-08-11 23:54 UTC, bishoymelek approved these changes
:tada:

2021-08-17 11:27 UTC, penk85 approved these changes

2021-09-06 14:43 UTC, merged