F/wpc 537 Peering CTA URLs to be checked
wepublish/wepublish pull request #391
Opened 2021-10-18 13:31 UTC by lakeside763

PR: New Features
Validating callToActionURLs

![invalid_url](https://user-images.githubusercontent.com/13334774/137741370-43d6f6c2-de38-4714-9d99-52c8791c92b5.jpg)

2021-11-01 10:00 UTC, bishoymelek commented on packages/editor/src/client/atoms/formControlUrl.tsx
> +      if (isValidURL) {
instead of line 20 till 24, maybe:
```
setInvalidInput(!isValidURL)
 ```

2021-11-01 10:03 UTC, bishoymelek commented on packages/editor/src/client/panel/peerProfileEditPanel.tsx
> +  useEffect(() => {
@lakeside763 @roosnic1 isn't it duplicating the validation? inside the new component and in the route again.

2021-11-01 10:06 UTC, roosnic1 requested changes

2021-11-01 10:06 UTC, roosnic1 commented on packages/editor/src/client/panel/peerProfileEditPanel.tsx
> +      const isValidImageURL = validateURL(callToActionImageURL ?? '')
Why would you want to validate an empty string?

2021-11-02 08:33 UTC, roosnic1 approved these changes
🎉

2021-11-02 08:52 UTC, penk85 approved these changes

2021-11-02 11:22 UTC, camilleory approved these changes

2021-11-02 15:09 UTC, merged