F/wpc 538 add call to action string
wepublish/wepublish pull request #415
Opened 2021-11-15 09:27 UTC by lakeside763

2021-11-16 11:40 UTC, bishoymelek commented on packages/api/package.json
> -    "jest": "^26.4.2",
I can't get it :) why did you remove jest?

2021-11-25 15:18 UTC, camilleory approved these changes

2021-11-29 08:35 UTC, bishoymelek submitted a review, later dismissed
🎉

2021-11-30 08:54 UTC, penk85 submitted a review, later dismissed

2021-12-01 16:12 UTC, roosnic1 requested changes
Looks good but still needs some changes.

2021-12-01 16:12 UTC, roosnic1 commented on packages/api-db-mongodb/src/migration.ts
> +              callToActionString: richTextToString('', peerProfile?.callToActionText)
the `?` is not necessary if you check above if `peerProfile` exists.

2021-12-01 16:12 UTC, roosnic1 commented on packages/api/src/graphql/peer.ts
> +    callToActionText: {type: GraphQLRichText},
why did you remove the `GraphQlNonNull` from `callToActionText`?

2021-12-01 16:12 UTC, roosnic1 commented on packages/editor/src/client/api/peer.graphql
>    callToActionText
in the editor you can remove `callToActionText` there it's not needed anymore

2021-12-14 08:14 UTC, penk85 commented on examples/website/src/shared/route/articleTemplateContainer.tsx
>            <a target="_blank" rel="noreferrer" href={peer?.callToActionURL}>
Wouldn't the `callToActionText` also be possible to be empty here? Shouldn't the `callToActionText` and `callToActionString` both be rendered conditionally, independently?

2021-12-14 09:42 UTC, penk85 commented on packages/api-db-mongodb/src/migration.ts
> -    // add slug to existing paymentMethods
Why did you remove this line?

2022-02-14 08:26 UTC, closed without merging