Update of stripePaymentProvider
wepublish/wepublish pull request #423
Opened 2021-11-22 16:25 UTC by roosnic1

2021-11-23 16:04 UTC, tomaszdurka requested changes

2021-11-23 16:04 UTC, tomaszdurka commented on packages/api/src/payments/stripePaymentProvider.ts
> +            payment_method: typeof paymentMethod === 'string' ? paymentMethod : paymentMethod?.id,
Took me a while you expect this multi-type paymentMethod - that's historical then. If this is always an `string` `id`, I would keep it as `string`/`null` only.

2021-11-23 16:04 UTC, tomaszdurka commented on packages/api/src/payments/stripePaymentProvider.ts
> +            payment_method: typeof paymentMethod === 'string' ? paymentMethod : paymentMethod?.id,
Plus even rename this to `paymentMethodId`.

2021-11-24 09:49 UTC, penk85 approved these changes

2021-11-24 10:12 UTC, bishoymelek approved these changes

2021-11-24 10:43 UTC, camilleory approved these changes

2021-11-24 12:20 UTC, tomaszdurka approved these changes

2021-11-24 12:20 UTC, merged