f/wpc-600 preview link
wepublish/wepublish pull request #483
Opened 2022-01-13 09:59 UTC by camilleory

Preview Button added to article and pages editor, take the user the a temporary preview of the article or page (link valid for 1 hour)
![Jan-13-2022 13-59-34](https://user-images.githubusercontent.com/58177575/149334869-c9753aa0-0b8b-4d17-931a-de610d250280.gif)

2022-01-17 10:14 UTC, camilleory commented on packages/editor/src/client/routes/articleEditor.tsx
> +                  disabled={hasChanged || !id}
I'd like to write a new ticket for that if that's ok

2022-01-17 10:15 UTC, camilleory commented on packages/editor/src/client/routes/articleEditor.tsx
> +                  disabled={hasChanged || !id}
I'd like to write a new ticket for that if that's ok

2022-01-17 10:21 UTC, camilleory commented on packages/editor/src/client/routes/articleEditor.tsx
> +                    window.open(data?.articlePreviewLink || '')
I get this error if I do: `Invalid hook call. Hooks can only be called inside of the body of a function component.`
Should I find a way around it or is it ok to leave the query outside ?

2022-01-17 10:22 UTC, roosnic1 commented on packages/editor/src/client/routes/articleEditor.tsx
> +                  disabled={hasChanged || !id}
@camilleory 👍🏾

2022-01-17 14:48 UTC, roosnic1 requested changes
Much better. Just some tiny changes.

2022-01-17 14:48 UTC, roosnic1 commented on packages/editor/src/client/routes/articleEditor.tsx
> +                    await previewLinkRefetch({id: id, hours: 1})
`previewLinkRefetch()` returns the data here and you should use that link to open a new window or not.

2022-01-17 14:48 UTC, roosnic1 commented on packages/editor/src/client/routes/articleEditor.tsx
> +                    window.open(data?.articlePreviewLink || '')
Also if `previewLinkRefetch()` doesn't return anything you shouldn't open a new tab. Here you can just do nothing if the query doesn't return a link,

2022-01-17 17:36 UTC, penk85 submitted a review, later dismissed

2022-01-18 13:11 UTC, roosnic1 approved these changes
👍🏾

2022-01-18 15:31 UTC, bishoymelek approved these changes
🎉

2022-01-18 15:41 UTC, penk85 approved these changes

2022-01-19 08:39 UTC, merged