F/wpc 620 peered articles list
wepublish/wepublish pull request #523
Opened 2022-02-24 09:29 UTC by camilleory

- Peered articles list filterable by title and by peer
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/58177575/155496927-2bacce9b-6d56-42bc-aee0-93b7a9c197ea.png">

2022-03-02 12:37 UTC, roosnic1 requested changes
looks very good i left some suggestions

2022-03-02 12:37 UTC, roosnic1 commented on packages/api/src/graphql/query.private.ts
> +          const peer = peers.filter(peer => (peerFilter ? peer.name === peerFilter : peer))[index]
here you should also return `true` instead of peer.

2022-03-02 12:37 UTC, roosnic1 commented on packages/editor/src/client/route.tsx
> +export const PeerArticleListRoute = route(RouteType.PeerArticleList, routePath`/peeredarticles`)
I suggest to change the path to `/peerarticles`

2022-03-02 12:37 UTC, roosnic1 commented on packages/editor/src/client/routes/peerArticleList.tsx
> +    errorPolicy: 'ignore'
why?

2022-03-02 12:37 UTC, roosnic1 commented on packages/editor/src/client/routes/peerArticleList.tsx
> +        duration: 5000
error messages should not be auto closed.

2022-03-02 12:37 UTC, roosnic1 commented on packages/editor/src/client/routes/peerArticleList.tsx
> +      {allPeers.length >= 2 ? (
I would always display the `<selectPicker>`. It makes the UI more consistent.

2022-03-03 09:51 UTC, tomaszdurka approved these changes
lgtm

2022-03-04 08:16 UTC, roosnic1 requested changes
Looks very good. Just one last thing.

2022-03-04 08:16 UTC, roosnic1 commented on packages/api/src/graphql/query.private.ts
> +          const peer = peers.filter(peer => (peerFilter ? peer.name === peerFilter : true))[index]
True. @camilleory i guess it makes sense to filter the `peers` on line 661. This way we only have to do it once.

2022-03-04 12:18 UTC, roosnic1 requested changes

2022-03-04 12:18 UTC, roosnic1 commented on packages/api/src/graphql/query.private.ts
> +        peers.filter(peer => (peerFilter ? peer.name === peerFilter : true))
This does not work. `filter()` returns a new array with the filtered elements. But you can write it all on one line.

`const peers = await dbAdapter.peer.getPeers().filter(peer => (peerFilter ? peer.name === peerFilter : true))`

2022-03-07 10:14 UTC, penk85 approved these changes
This looks and works great

2022-03-07 12:31 UTC, roosnic1 approved these changes
👍🏾

2022-03-09 13:03 UTC, penk85 approved these changes

2022-03-09 13:10 UTC, tomaszdurka approved these changes
lgtm

2022-03-09 13:54 UTC, merged