added env variables to .env.example files
wepublish/wepublish pull request #533
Opened 2022-03-15 10:52 UTC by camilleory

2022-03-28 11:05 UTC, tomaszdurka requested changes

2022-03-28 11:05 UTC, tomaszdurka commented on examples/api/.env.example
> +# PORT
If you comment something which you can uncomment, you should not add extra space. 

Make it
```
#PORT=
```

Same goes for others.

2022-03-28 11:05 UTC, tomaszdurka commented on examples/api/.env.example
> +# PORT
Space you usually add when you want to add a pernament comment e.g.
```
# Here is the beloved Stripe configuration
```

2022-03-28 21:51 UTC, tomaszdurka approved these changes

2022-03-30 11:40 UTC, tomaszdurka approved these changes

2022-03-30 11:40 UTC, tomaszdurka commented
As discussed this is good start for improving documentation.
Let's merge as is and we can improve docu and setup itself in other prs.

2022-03-30 12:11 UTC, penk85 approved these changes

2022-04-12 11:21 UTC, merged