wpc-582 Add package version in the editor
wepublish/wepublish pull request #538
Opened 2022-03-16 13:38 UTC by tomaszdurka

2022-03-17 14:16 UTC, camilleory submitted a review, later dismissed

2022-03-23 11:46 UTC, tomaszdurka commented
@elias-summermatter @michael-scheurer do you think that helps. or something more visible with api version too?

2022-04-08 07:43 UTC, elias-summermatter requested changes

2022-04-08 07:43 UTC, elias-summermatter commented on packages/api/__tests__/api/private/index.ts
> +  tags?: Maybe<Array<Scalars['String']>>
Why?

2022-04-08 07:43 UTC, elias-summermatter commented on packages/api/__tests__/api/private/index.ts
> +  tags?: Maybe<Array<Scalars['String']>>
Why?

2022-04-08 07:43 UTC, elias-summermatter commented on packages/api/__tests__/api/private/index.ts
> +  tags: Array<Scalars['String']>
Why?

2022-04-08 07:43 UTC, elias-summermatter commented on packages/editor/src/server/index.tsx
> +          <title>WePublish Editor (v{process.env.npm_package_version})</title>
This does not work as we tested together :-)

2022-04-08 07:45 UTC, michael-scheurer reviewed
I think you're mixing up TikTok videos with system information. Why?

Secondly, to have the current version visible is nice to have. In my opinion it really doesn't solve the original issue from Jira which is described as "As a developer i want a clear release strategy".
A clear release strategy has to be implemented over organisation and not code ;)

2022-04-08 07:45 UTC, michael-scheurer commented on packages/api/src/context.ts
> +    async getSystemInformation(): Promise<SystemInformation> {
A function should always come with a minimum of comments. As a dev I want to know why this function and what it does.

2022-04-08 07:47 UTC, michael-scheurer commented on packages/api/src/graphql/query.public.ts
> +    getSystemInformation: {
This information should never be public. Avoid telling the world, which bugs you have in your application.

2022-06-08 09:28 UTC, tomaszdurka commented
Closing for now.

2022-06-08 09:28 UTC, closed without merging