b/WPC-655: As a publisher, i want mailto-Links without slashes (//)
wepublish/wepublish pull request #540
Opened 2022-03-17 16:44 UTC by elias-summermatter

2022-03-17 18:05 UTC, elias-summermatter commented on packages/editor/src/client/blocks/richTextBlock/toolbar/linkMenu.tsx
> +    const pattern = new RegExp('^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}$', 'i')
Yes but the one from the rfc looks like this and i taught this is a bit to much for an optional validation and no one understands this one the one is a simplified one that is easy readable which covers most of the cases:
 `(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])`

2022-03-17 18:07 UTC, elias-summermatter commented on packages/editor/src/client/blocks/richTextBlock/toolbar/linkMenu.tsx
> +          {prefix !== prefixType.mailto && url && !isValidURL ? (
I taught about that but for me its more "react" stile like this and its simpler if one oft the other reviewers disagrees with me on this one i can change it.

2022-03-23 09:02 UTC, penk85 approved these changes

2022-03-23 09:06 UTC, camilleory approved these changes

2022-03-28 10:41 UTC, tomaszdurka commented on packages/editor/src/client/blocks/richTextBlock/toolbar/linkMenu.tsx
> +          {prefix !== prefixType.mailto && url && !isValidURL ? (
I am not a fan of using if not-mailto for all the other urls.

2022-03-28 10:41 UTC, tomaszdurka commented on packages/editor/src/client/blocks/richTextBlock/toolbar/linkMenu.tsx
> +    const pattern = new RegExp('^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}$', 'i')
Is there any other concern than readibility? If no I would go for RFC and just store under constant.

2022-03-28 10:56 UTC, tomaszdurka requested changes

2022-03-28 10:56 UTC, tomaszdurka commented on packages/editor/src/client/blocks/richTextBlock/toolbar/linkMenu.tsx
> +      validateMail(url).then(value => setIsValidMail(value))
Guys, let's rather implement `validateLink(prefix, url)` and only use `isValidLink`.

2022-03-30 08:48 UTC, merged