filter consistency
wepublish/wepublish pull request #606
Opened 2022-05-31 11:46 UTC by camilleory

2022-05-31 13:02 UTC, Itrulia commented on packages/editor/src/client/panel/teaserSelectPanel.tsx
> +  // const [peerFilter, setPeerFilter] = useState<ArticleFilter>({title: ''})
I know you haven't opened this up for review yet but I wanted to let you know that the peerFilter works a bit different and the filter in the peerArticles is not actually used (or even defined in the args).

peerFilter checks for the name of the peer:

```
.filter(peer => (peerFilter ? peer.name === peerFilter : true))
```

2022-06-08 11:26 UTC, tomaszdurka commented
@camilleory please let me know what is the status of this one, do you need something here?

2022-06-08 11:38 UTC, camilleory commented
Yes @tomaszdurka it's for this branch I've been asking to check the filter behaviour

2022-09-22 10:09 UTC, Itrulia commented on packages/api/__tests__/utility.ts
> +  getPeeredArticleURL(peer: Peer, article: Article): string {
Shouldn't this be PublicArticle? Since the website only gets PublicArticle and not Article?

2022-09-22 10:13 UTC, Itrulia reviewed
Looks good, I have 2 question 1 was regarding the Article/PeerArticle thing.
The other is I think Camille wanted to add pagination to the peers too, but we can add this in a later PR since it's not in the acceptance criteria.

2022-09-23 10:26 UTC, Itrulia approved these changes

2022-09-27 09:04 UTC, michael-scheurer requested changes
I think, your changes are looking good. But I'm not sure, if the PR implements what was requested from the author of the original story. So for example I can't see or find any filter in the UI like mentioned in the story:

title: String
draft: Boolean
published: Boolean
pending: Boolean
authors: [ID!]
tags: [String!]

@camilleory Would you mind to have a look on it?

2022-09-29 11:11 UTC, michael-scheurer approved these changes

2022-09-29 11:38 UTC, penk85 approved these changes

2022-09-29 11:40 UTC, merged