WPC 679 remove tmp user
wepublish/wepublish pull request #610
Opened 2022-06-01 13:29 UTC by elias-summermatter

2022-06-01 14:47 UTC, elias-summermatter commented
@tomaszdurka Please review as asap, that i can merge it soon :-)  => I know the tests are not running but thats because the test not running on master too :-)

2022-06-03 12:12 UTC, elias-summermatter commented
@michael-scheurer Can you have a look at my changes to your migration?

2022-06-03 12:13 UTC, elias-summermatter commented
@tomaszdurka can you approve this pull request that i can merge it?

2022-06-07 12:02 UTC, elias-summermatter commented
@tomaszdurka please can you chech?

2022-06-08 05:24 UTC, Itrulia requested changes

2022-06-08 05:24 UTC, Itrulia commented on packages/api-db-mongodb/src/migration.ts
> +    async migrate(db) {
this should probably be v22 and not 21

2022-06-08 07:18 UTC, Itrulia submitted a review, later dismissed

2022-06-08 09:26 UTC, tomaszdurka approved these changes

2022-06-08 09:26 UTC, tomaszdurka commented on packages/api-db-mongodb/src/migration.ts
> +        await tempUser.rename('temp.users.bak')
We don't need to migrate temp users to users at all?

2022-06-08 13:40 UTC, Itrulia approved these changes

2022-06-09 07:00 UTC, Itrulia approved these changes

2022-06-09 07:06 UTC, tomaszdurka approved these changes

2022-06-09 07:06 UTC, merged