Analytics readme
wepublish/wepublish pull request #671
Opened 2022-08-22 15:42 UTC by antkiewiczk

2022-08-23 06:53 UTC, Itrulia approved these changes

2022-08-25 10:08 UTC, camilleory commented on docs/README.md
> +The tracker will automatically look in the html structure for an element with a specific id and take data from this element. Example element to send peer tracking data should look like the following:
Here I would add where the specific id is retrieved from, I was missing this explanation to understand how it works before asking you.

2022-08-25 13:09 UTC, camilleory approved these changes

2022-08-30 12:38 UTC, tomaszdurka requested changes

2022-08-30 12:38 UTC, tomaszdurka commented on docs/README.md
> +In order to use analytics and send data to WePublish's Matomo, we prepared an analytics.js plugin that's available here:
I would not really mention about matomo directly here. Only note on the very bottom.

2022-08-30 12:38 UTC, tomaszdurka commented on docs/README.md
> +    import { matomoPlugin } from '@wepublish/analytics'
Also here, I would not mention it's `matomoPlugin`... 
Ah that's what we actually create in analytics. Not sure if that's good idea. If we change the underlying solution `matomoPlugin` doesn't correspond well.

What about using plugin `WepublishPlugin`?

2022-08-30 16:05 UTC, tomaszdurka commented on docs/README.md
> +    import { matomoPlugin } from '@wepublish/analytics'
Yes, let's call the plugin `wepublish` so when you initiate "analytics" with "wepublish" plugin.

2022-09-01 09:04 UTC, Itrulia approved these changes

2022-09-12 06:55 UTC, tomaszdurka approved these changes

2022-09-12 07:44 UTC, merged