feat(editor,api,db,example): HTML Block
wepublish/wepublish pull request #683
Opened 2022-08-30 14:19 UTC by antkiewiczk

2022-09-12 09:23 UTC, Itrulia requested changes

2022-09-12 09:23 UTC, Itrulia commented on packages/editor/src/client/locales/fr.json
> +      "payedUntil": "Payé jusqu'à",
Merge error

2022-09-12 09:23 UTC, Itrulia commented on packages/editor/src/client/locales/de.json
> +      "payedUntil": "Bezahlt bis",
Merge error

2022-09-12 09:23 UTC, Itrulia commented on packages/editor/src/client/panel/htmlEditPanel.tsx
> +  const [input, setInput] = useState<HTMLBlockValue>(value)
We don't need input just `htmlBlock`

2022-09-12 09:23 UTC, Itrulia commented on packages/editor/src/client/panel/htmlEditPanel.tsx
> +  useEffect(() => {
This is not needed when input is being replaced

2022-09-12 12:40 UTC, Itrulia approved these changes

2022-09-13 12:52 UTC, tomaszdurka approved these changes
Looks good, a little bit of security issues with setting especially in editor. But let's say it's good :)

2022-09-13 12:52 UTC, tomaszdurka commented on packages/editor/src/client/blocks/htmlBlock.tsx
> +              <div style={{marginTop: '30px'}} dangerouslySetInnerHTML={{__html: value.html}} />
What do you think about not showing it in editor? :)

2022-09-13 13:09 UTC, tomaszdurka approved these changes

2022-09-13 13:12 UTC, Itrulia approved these changes

2022-09-13 13:17 UTC, merged