migration for peerInformation table
wepublish/wepublish pull request #684
Opened 2022-08-30 15:41 UTC by penk85

2022-08-31 12:30 UTC, Itrulia commented on packages/api/prisma/schema.prisma
> +model ArticlePeerInformation {
Do we want to have the information here if the article has been edited?

2022-08-31 12:34 UTC, Itrulia commented on packages/api/prisma/schema.prisma
> +}
Missing `@@map('articles.peer-information')` to set the table name. Else the table name is `ArticlePeerInformation`

2022-09-06 06:51 UTC, Itrulia submitted a review, later dismissed

2022-09-14 08:19 UTC, elias-summermatter requested changes

2022-09-14 08:19 UTC, elias-summermatter commented on packages/api/prisma/migrations/20220905153523_peering/migration.sql
> +CREATE UNIQUE INDEX "articles.peer-information_producerArticleId_key" ON "articles.peer-information"("producerArticleId");
Shouldn't that be combined unique constraint with peerId?

2022-10-26 06:52 UTC, closed without merging

2022-10-26 06:52 UTC, tomaszdurka commented
Closing in favor of https://github.com/wepublish/wepublish/pull/734