Prevent canceled invoices from marked as paid
wepublish/wepublish pull request #689
Opened 2022-09-07 08:19 UTC by elias-summermatter

2022-09-07 14:01 UTC, michael-scheurer requested changes
There are a lot of changes, where it seems they are coming from an internal IDE linting rule. We should not add that in this pr. It's hardly reviewable.

Also, I cannot see any change in the api, which would solve "If a new subscription is created, then deactivated, reactivated and then paid there is a mess with periods". How come?

2022-09-07 14:07 UTC, elias-summermatter commented on packages/editor/src/client/atoms/formControlUrl.tsx
> +import React, {useCallback, useState} from 'react'
Sure, the fix is that we prevent user from mark canceled invoices as paid.

2022-09-07 14:08 UTC, elias-summermatter commented on packages/editor/src/client/atoms/formControlUrl.tsx
> +import React, {useCallback, useState} from 'react'
This is just the normal linting of the project which nobody did. And if its ok i will not revert this. :-)

2022-09-13 13:52 UTC, michael-scheurer commented on packages/editor/src/client/atoms/formControlUrl.tsx
> +import React, {useCallback, useState} from 'react'
I think the linting is always done pre-commit via husky. See package.json in the root folder.

"husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged --pattern \"{examples,packages,services}/**/*.{js,ts,tsx,json}\""
    }
  },

2022-09-14 06:43 UTC, elias-summermatter commented
@michael-scheurer @Itrulia  please review that i can merge it an close this issue today.

2022-09-14 06:56 UTC, Itrulia approved these changes

2022-09-14 07:09 UTC, michael-scheurer approved these changes

2022-09-14 07:11 UTC, merged