Draft:F/wpc 880 add comment context
wepublish/wepublish pull request #700
Opened 2022-09-15 09:04 UTC by michael-scheurer

2022-11-01 17:31 UTC, michael-scheurer commented
This pr implements a comment history in the comment edit view as well as in the article metadata view.

![image](https://user-images.githubusercontent.com/70939054/199299157-642ab841-7efa-4260-88e0-f262515d0d7c.png)

2022-11-09 09:29 UTC, Itrulia commented on packages/editor/src/client/atoms/comment/commentHistory.tsx
> +  const {data, refetch} = useCommentListQuery({
I guess this should use a LazyQuery as the useEffect below is called immediately

2022-11-09 09:33 UTC, Itrulia requested changes
Works amazing and looks fine (I have a question about a lazy query but it's non blocking for me). The only thing I found is that this now breaks the layout at default zoom level on my MacBook when the context is expanded. Screenshots are below

<img width="1561" alt="Screenshot 2022-11-09 at 10 31 19" src="https://user-images.githubusercontent.com/1131901/200793376-84275d56-4304-4405-87e1-3437fa0f79e3.png">
<img width="1561" alt="Screenshot 2022-11-09 at 10 31 22" src="https://user-images.githubusercontent.com/1131901/200793397-5c912cbb-7b36-4aca-a59c-662d13e0fb3e.png">

2022-11-09 10:59 UTC, penk85 reviewed
Looks really good and useful feature. I'd suggest maybe a clear visual indication for the current comment besides open drop down (maybe highlighted border or bold and to put other comments in gray text, possibly smaller.) . I also wonder if the edit text box could go inside the comment preview to simplify the ui.

2022-12-15 15:31 UTC, Itrulia commented on packages/editor/src/client/atoms/comment/commentHistory.tsx
> +          id={childComment.id === originComment?.id ? 'current-comment' : ''}>
Could this result in multiple 'current-comment' ids?

2022-12-15 17:03 UTC, penk85 reviewed
:+1:

2022-12-19 09:02 UTC, penk85 approved these changes

2022-12-19 09:06 UTC, Itrulia approved these changes

2022-12-19 09:19 UTC, merged