R/release 8.0.0 seccom.0
wepublish/wepublish pull request #731
Opened 2022-10-19 09:36 UTC by elias-summermatter

2022-10-26 11:50 UTC, tomaszdurka commented
@elias-summermatter I've rebased PR to 8.0.0 release. So we can merge into that one and then back to prod and master.

2022-10-26 11:57 UTC, tomaszdurka commented
@elias-summermatter Additionally I can see some new features compared to 8.0.0. 
Are these are all bugfixes from your perspective? If these are not really bugfixes, but missing functionalities we should rather merge these to master and plan yet another release.

2022-11-01 08:03 UTC, Itrulia requested changes

2022-11-02 09:49 UTC, michael-scheurer commented on packages/api/src/graphql/comment/comment.public-queries.ts
> +    title: revisions.length ? revisions[revisions.length - 1].title : null,
Current target library in tsconfig doesn't allow it for now. Unfortunately

2022-11-02 09:56 UTC, michael-scheurer commented on packages/api/src/context.ts
> +          intentID: `${intent.intentID}`,
This is intended, @elias-summermatter sais.

2022-11-02 09:56 UTC, michael-scheurer commented on packages/api/src/context.ts
> +          intentID: `${intent.intentID}`,
This is intended, @elias-summermatter sais.

2022-11-02 10:08 UTC, michael-scheurer commented
Closing in favor of https://github.com/wepublish/wepublish/pull/745

2022-11-02 10:08 UTC, closed without merging