feat(editor): add properties fields to user edit
wepublish/wepublish pull request #771
Opened 2022-11-18 11:56 UTC by antkiewiczk

2022-11-21 08:20 UTC, michael-scheurer requested changes
Looks good. One small bug: If I create a new user with properties, the properties are not created, but only the user.

2022-11-21 12:01 UTC, Itrulia approved these changes

2022-11-22 08:01 UTC, Itrulia approved these changes

2022-11-22 08:06 UTC, michael-scheurer approved these changes

2022-11-22 09:02 UTC, penk85 approved these changes

2022-11-22 09:49 UTC, merged