chore: replace yarn with npm
wepublish/wepublish pull request #802
Opened 2023-01-04 12:45 UTC by Itrulia

2023-01-04 14:37 UTC, Itrulia commented on .env.local
> -# Editor
Shouldn't have been commited

2023-01-05 07:53 UTC, Itrulia commented on docs/README.md
> +   <<<<<<< HEAD
Merge conflict

2023-01-05 07:53 UTC, tomaszdurka commented on docs/README.md
> +   > > > > > > > master
should this be here?

2023-01-05 07:55 UTC, tomaszdurka commented on lerna.json
> +  "version": "10.0.0-alpha.1",
oh what's up with this?

2023-01-05 09:01 UTC, Itrulia commented on lerna.json
> +  "version": "10.0.0-alpha.1",
That's from my testing :D

2023-01-05 09:06 UTC, Itrulia commented on libs/api/__tests__/specs/peer.test.ts
> -        logoID: 'logoID123',
This was causing an error and the snapshot included it. We don't have any image uploads in tests so far so I deleted it for now.

2023-01-05 09:08 UTC, Itrulia commented on .npmrc
> +legacy-peer-deps=true
Without it we get an error because of @karma.run requiring React 16 in peerDeps

2023-01-05 09:37 UTC, tomaszdurka requested changes
I just found this one yarn in the project still.

```
https://github.com/wepublish/wepublish/blob/f/WPC-963-remove-yarn/config/create-gke-manifest.js
```

Apart from that looks great !

2023-01-05 09:44 UTC, Itrulia commented
Good catch @tomaszdurka, updated

2023-01-05 10:05 UTC, tomaszdurka submitted a review, later dismissed

2023-01-05 10:53 UTC, Itrulia commented on helm/charts/wepublish/templates/deployment-api.yaml
> +          args: ['-c', 'npx prisma migrate deploy && npx ts-node libs/api/prisma/run-seed.ts && node dist/libs/api/src/runServer.js']
No, npx is for binaries such as prisma. npm run is for scripts inside the package.json

2023-01-05 12:16 UTC, merged