WPC-788: Subscription edit as separate view
wepublish/wepublish pull request #832
Opened 2023-01-24 11:59 UTC by antkiewiczk

2023-01-27 17:14 UTC, tomaszdurka commented
@antkiewiczk is this part of specific task ?

2023-01-30 09:09 UTC, Itrulia submitted a review, later dismissed

2023-01-30 09:23 UTC, tomaszdurka commented on apps/editor/src/app/routes/userEditView.tsx
> +                  <UserSubscriptionsList subscriptions={user?.subscriptions} userId={user?.id} />
Render whole Subscription Column only if the user exists. Get rid of `user?.*`

2023-02-02 12:05 UTC, michael-scheurer requested changes
Good work! See one comment in the code and the screenshot below. Also you might align the deactivate button. I would move it to the top right part. See for example how we did it on the comment single view.

![image](https://user-images.githubusercontent.com/70939054/216319671-7b8e4d30-305f-4f7a-944d-59e695a46cba.png)

2023-02-02 12:05 UTC, michael-scheurer commented on apps/editor/src/app/routes/subscriptionList.tsx
> +        <SubscriptionEditView
This drawer can be removed. Instead you need to route the user.

2023-02-06 09:06 UTC, Itrulia approved these changes

2023-02-07 09:02 UTC, penk85 approved these changes

2023-02-07 10:20 UTC, michael-scheurer approved these changes

2023-02-07 10:28 UTC, merged