enh/libs-utils
wepublish/wepublish pull request #835
Opened 2023-01-26 14:18 UTC by michael-scheurer

2023-01-30 08:16 UTC, Itrulia approved these changes

2023-02-07 13:04 UTC, Itrulia approved these changes

2023-02-07 13:06 UTC, Itrulia commented on apps/editor/__tests__/specs/__snapshots__/utility.test.ts.snap
> +exports[`slugify should transform text with special ss like ß correctly 1`] = `"text-with-special-ss-like-s"`;
should this be ss or s? ß should be ss technically. One slugify method did this correctly, the other didn't.

2023-02-07 13:07 UTC, Itrulia requested changes
ß question open, else approved

2023-02-08 11:50 UTC, Itrulia approved these changes

2023-02-08 11:52 UTC, Itrulia requested changes

2023-02-08 11:52 UTC, Itrulia commented on apps/editor/__tests__/specs/__snapshots__/utility.test.ts.snap
> +exports[`slugify should transform text with umlaute like ä ö and ü correctly 1`] = `"text-with-umlaute-like-a-o-and-u"`;
Sorry I missed it earlier, same thing here: https://wepublish.atlassian.net/browse/WPC-242

2023-03-15 12:20 UTC, tomaszdurka commented
@michael-scheurer can you update this one quickly, get review and merge please ? :)

2023-03-16 10:59 UTC, michael-scheurer commented
> @michael-scheurer can you update this one quickly, get review and merge please ? :)

@tomaszdurka I'm not able to merge, since the tests are failing on master. Could you fix that first? Every thing else is done in that branch and is now ready to be merged.

2023-03-16 13:55 UTC, tomaszdurka commented
@michael-scheurer OK. Thanks for merging. Will wait for master to be fixed.

2023-03-18 16:38 UTC, LukasSkywalker submitted a review, later dismissed

2023-03-22 11:13 UTC, Itrulia approved these changes

2023-11-24 14:52 UTC, closed without merging