add onDelete relation to session
wepublish/wepublish pull request #837
Opened 2023-01-26 16:17 UTC by antkiewiczk

2023-01-26 16:21 UTC, Itrulia requested changes

2023-01-26 16:21 UTC, Itrulia commented on libs/api/prisma/migrations/20230126155832_session_on_delete_cascade/migration.sql
> +ALTER TABLE "articles.revisions.author" DROP CONSTRAINT "articles.revisions.author_authorId_fkey";
Theres a lot going on here that shouldnt be here. 

Have you had by chance the GUID branch checked out once and ran migrations there?

2023-01-27 10:03 UTC, Itrulia approved these changes

2023-01-27 17:02 UTC, tomaszdurka approved these changes

2023-01-27 17:02 UTC, merged