feat(890): settings - warnings, tooltips, hide from non-admin
wepublish/wepublish pull request #845
Opened 2023-01-31 17:39 UTC by antkiewiczk

2023-02-01 07:59 UTC, Itrulia commented on apps/editor/src/app/base.tsx
> +                <PermissionControl qualifyingPermissions={['CAN_UPDATE_SETTINGS']}>
Is that on purpose that the CAN_GET_SETTINGS isn't needed anymore?

2023-02-01 09:39 UTC, Itrulia commented on apps/editor/src/app/base.tsx
> +                <PermissionControl qualifyingPermissions={['CAN_UPDATE_SETTINGS']}>
Then we should remove CanGetSettings from the editor's permission instead. There's other places (like the actual component) where that permission is also used.

2023-02-01 09:40 UTC, Itrulia requested changes
CanGetSettings should be removed from the editor's permission instead

2023-02-01 10:20 UTC, michael-scheurer requested changes
Great work. Just one detail. Could we improve the look of the info icon a little bit? I would consider to display the info icon not surrounded by a button.
Thus, the icon as it is, but in blue and remove the outer button boundary. What do you think?

2023-02-01 12:41 UTC, penk85 commented on libs/api/src/lib/graphql/permissions.ts
> -  CanGetSettings,
I think we should still keep this permission in the api. Just remove the qualifying permission of "CAN_GET_SETTINGS" from the settings page .

2023-02-01 12:44 UTC, penk85 requested changes
Looks great. Just I'd keep the permission in the api and update in the editor. Both the settingList and the settings tab in the base sidebar.

2023-02-02 08:11 UTC, penk85 commented on libs/api/src/lib/graphql/permissions.ts
> -  CanGetSettings,
Ah you're right. This makes sense.

2023-02-02 08:12 UTC, penk85 approved these changes

2023-02-02 08:57 UTC, michael-scheurer approved these changes

2023-02-02 08:58 UTC, merged