Consents
wepublish/wepublish pull request #872
Opened 2023-03-09 16:52 UTC by antkiewiczk

2023-03-15 12:32 UTC, tomaszdurka commented
looked !

2023-03-29 08:24 UTC, penk85 commented on libs/consent/editor/src/lib/consent-list.tsx
> +        {/* todo permission control */}
Is this still to be done?

2023-03-29 08:32 UTC, penk85 commented on libs/consent/editor/src/lib/consentEditView.tsx
> +        {`A consent with slug '${slug}' already exists. Please choose a different slug.`}
I'm guessing the error message isn't helpful here? Can we use translations for this?

2023-03-29 08:37 UTC, penk85 commented on libs/consent/editor/src/lib/consentForm.tsx
> +            placeholder={t('userSubscriptionEdit.selectMemberPlan')}
Did you want the member plan placeholder?

2023-03-30 11:01 UTC, Itrulia requested changes

2023-04-03 08:36 UTC, tomaszdurka requested changes
Remove `Unset` value from `ConsentValue`, change `ConsentValue` to simple `boolean`.

2023-04-04 14:06 UTC, tomaszdurka commented on libs/consent/editor/rsuite.d.ts
> +}
This cannot be loaded  from rsuite??

2023-04-04 14:07 UTC, tomaszdurka commented on libs/consent/editor/src/apiClientv2.ts
> +import {ApolloClient, ApolloLink, createHttpLink, InMemoryCache} from '@apollo/client'
Why we have this code in here? Do we need this in every module now?

2023-04-05 07:01 UTC, tomaszdurka commented on libs/consent/editor/src/apiClientv2.ts
> +import {ApolloClient, ApolloLink, createHttpLink, InMemoryCache} from '@apollo/client'
@Itrulia can you add your thoughts?

2023-04-05 11:41 UTC, Itrulia commented on libs/api/prisma/schema.prisma
> +  UserConsent   UserConsent[]
Yes we should, but that's out of scope for this PR

2023-04-05 11:42 UTC, Itrulia commented on libs/api/prisma/schema.prisma
> +  UserConsent  UserConsent[]
```suggestion
  userConsents  UserConsent[]
```

2023-04-05 11:44 UTC, Itrulia commented on libs/consent/api/src/lib/userConsent/user-consent.service.ts
> +      where: {
```
where: {
   value: filter.value,
        consent: {
          name: filter.name,
          slug: filter.slug
        }
      },
```

Is probably what you wanted. Currently there's a bug here where value does nothing

2023-04-05 11:50 UTC, Itrulia commented on libs/consent/api/src/lib/userConsent/user-consent.service.ts
> +    if (!user.user.roleIDs.includes('admin') && user.user.id !== userConsent.userId) {
The service shouldn't be checking permissions but the resolver via decorators, this allows for things to be reused

2023-04-06 17:49 UTC, Itrulia approved these changes

2023-04-07 12:34 UTC, tomaszdurka approved these changes

2023-04-07 12:39 UTC, merged