WPC-1129: Importable events
wepublish/wepublish pull request #899
Opened 2023-04-27 16:38 UTC by antkiewiczk

NOTE: lots of these files are just atoms/blocks moved from editor to ui library

2023-05-25 12:05 UTC, Itrulia requested changes
We should delete the components in the editor that were moved out. Else we will be running into problems.

2023-05-25 12:05 UTC, Itrulia commented on libs/api/src/lib/graphql/event/event.query.ts
> +    .then(res => res.map(single => single.externalSourceId))
prob should use async await here

2023-05-25 12:05 UTC, Itrulia commented on libs/editor/api-v2/src/lib/graphql.ts
> +  description: Scalars['JSON'];
This should be RichText, no?

2023-05-25 12:37 UTC, antkiewiczk commented
> We should delete the components in the editor that were moved out. Else we will be running into problems.

but the components are used by other components in editor. Can this be done as separate PR? Probably together with this: https://wepublish.atlassian.net/browse/WPC-1199

2023-05-25 12:59 UTC, Itrulia commented
Whats the problem with importing them from the editor or am I missing something?

2023-05-25 13:32 UTC, antkiewiczk commented
> Whats the problem with importing them from the editor or am I missing something?

I don't think that it's possible to import the components from editor in an nx library. Moving components to libs/ui was introduced in previous task - consents, to solve this problem (being able to use atoms/blocks etc in libs/xxx). This is also when the components were duplicated and existed in editor and libs/ui. I can of course change this and import these components in editor and remove them, but this PR would be much bigger than now. I can of course do it in separate PR, but I asked about it some time ago and we decided to keep it together. I am aware of these problems (duplicating components, possibly having to change something twice - in editor and libs/ui etc), but this task is about importing events and I did it to make it work as this is the priority. That's why I proposed to do all of the components - atoms/blocks/panels etc in separate task, and I suggest doing it asap - right after merging this PR - to avoid similar problems in the future.

2023-05-30 10:27 UTC, tomaszdurka commented
Hey @antkiewiczk, cc @Itrulia  please move the UI moving from this PR.
We talked about it last Wednesday and we were clear in order to get smaller PR we need to plan our work better.
Additionally, currently the UI pieces are not moved, but copied which actually results in duplicated code and potential code split. 
It's probably like 2-3 hours of work to create the PR and then rebase this PR into the the new one another few.
Cheers !

2023-06-29 14:16 UTC, closed without merging