B/wep 90 navigation menu display
wepublish/wepublish pull request #91
Opened 2020-12-01 18:13 UTC by 0815pascal

2020-12-02 10:38 UTC, penk85 submitted a review, later dismissed

2020-12-02 15:04 UTC, roosnic1 requested changes
We need to choose a different approach.

2020-12-03 15:08 UTC, roosnic1 approved these changes

2020-12-03 15:17 UTC, bishoymelek approved these changes

2020-12-03 15:21 UTC, penk85 approved these changes

2020-12-03 15:53 UTC, faebebin approved these changes
Looks good.

2020-12-03 16:12 UTC, merged