F/wep 88 hide authors
wepublish/wepublish pull request #92
Opened 2020-12-02 10:33 UTC by penk85

Added option for publisher to hide authors of an article. This allows for authors to stay private.
Updated db schema and queries with new category, and set the public API to validate whether authors are hidden before returning article data. Editor was updated to allow toggling changes.

2020-12-02 14:54 UTC, roosnic1 requested changes
Looks very good 👍🏾

2020-12-03 08:40 UTC, penk85 commented on packages/api-db-mongodb/src/migration.ts
> +            type: 'graphqlteaserGrid',
Huh. Good catch.

2020-12-03 09:33 UTC, roosnic1 approved these changes
🎉

2020-12-03 15:55 UTC, faebebin approved these changes
Looks good.

2020-12-03 19:38 UTC, 0815pascal approved these changes

2020-12-07 09:31 UTC, bishoymelek approved these changes

2020-12-07 09:41 UTC, merged